### ISSUE TITLE
Link to poldrack.github.io/psych-open-science-guide from project page

### ISSUE THREAD

**Issue by effigies** [poldrack/psych-open-science-guide#9]
To make it easier to contribute, an "Edit on GitHub" link would be nice to have on each page. Looks like there's a plugin to do this: https://github.com/rtCamp/gitbook-plugin-edit-link

Can try to get this building locally and submit a PR if this isn't trivial for you.

Similarly, linking to the rendering from the project description and/or README would make it easier to go from looking at the markup to its rendering.

**Comment by poldrack** [comment]
thanks - Before doing this I am trying to decide whether to stick with gitbook or to use bookdown or jupyterbook. thoughts?

**Comment by effigies** [comment]
Nope. I haven't tried any of them, so can't give a worthwhile opinion.

**Comment by effigies** [comment]
Looks like the new rendering handles the "Edit on GitHub" part. Would also be useful to be able to get to the document from the repository.

**Comment by poldrack** [comment]
added the link to the About section

**Comment by effigies** [comment]
Cool, thanks! Reading through now.
